### ISSUE TITLE
combine.ics examples?

### ISSUE THREAD

**Issue by ctr49** [jacobmischka/ics-merger#1]
Do you have any working combine.ics examples?

I'm trying to combine multiple ics calendars (with just "{}" as .env.json) but the output from getIcalsFromUrls is always empty.

**Comment by jacobmischka** [comment]
For the web-based merging you mean? Specifying them as search parameters should be all you need to do, like this: https://jacobmischkaical-merger-njsbqjanno.now.sh/combine.ics?urls[]=http://www.calconnect.org/tests/PayDay.ics&urls[]=https://gist.githubusercontent.com/DeMarko/6142417/raw/1cd301a5917141524b712f92c2e955e86a1add19/sample.ics

This is on a clean instance using an empty .env.json file: https://jacobmischkaical-merger-njsbqjanno.now.sh/.env.json

**Comment by jacobmischka** [comment]
Glad to hear it's working now!
